### ISSUE TITLE
Time Units Conversion question about femtoseconds to atomic-unit-of-time

### ISSUE THREAD

**Issue by Psygoal** [ochsenfeld-lab/adaptive_sampling#14]
Why is the fs/a.u. defined in units.py equal to 1.0327503e0? Shouldn't it be 1/41.3?
```python
atomic_to_fs = 1.0327503e0
```

**Comment by ahulm** [comment]
Hi,

I agree that the term `atomic units` might be misleading. 
In fact, we are using `electron units`, as explained for example in this thread of the LAMMPS forum:

https://matsci.org/t/electron-units-documentation-issue/17986
